// The generated Figma development plugin (Spec 003, plan D-12). The maintainer imports it from its
// manifest in Figma desktop; development plugins run on every Figma plan, so the standard path does
// not depend on Organization or Enterprise. It applies `plan.json` — embedded as a constant, since
// a plugin reads no repository files — idempotently: it finds what it made by name and by the
// shared plugin data `fundamento`, updates it, and never duplicates. Nothing else in the file is
// touched. An agent can run the same code through the Figma MCP.
//
// The plugin uses this slice of the Plugin API (the test double covers exactly it):
// variables.getLocalVariableCollectionsAsync/getLocalVariablesAsync, createVariableCollection,
// createVariable, createVariableAlias, setBoundVariableForPaint, collection.addMode/renameMode,
// variable.setValueForMode, createComponent/createFrame/createText, combineAsVariants,
// appendChild, setBoundVariable, set/getSharedPluginData.

import type { FigmaPlan } from "./figma.js";

/** Part property -> the node and field the plugin binds it to (Celo knowledge, Art. VIII). */
const BINDINGS: Readonly<
  Record<string, { node: "control" | "label"; field: string; paint?: boolean }>
> = {
  "surface.fill": { node: "control", field: "fills", paint: true },
  "border.color": { node: "control", field: "strokes", paint: true },
  "border.width": { node: "control", field: "strokeWeight" },
  "box.height": { node: "control", field: "minHeight" },
  "box.width": { node: "control", field: "minWidth" },
  "box.inline-padding": { node: "control", field: "paddingLeft" },
  "box.gap": { node: "control", field: "itemSpacing" },
  "box.radius": { node: "control", field: "cornerRadius" },
  "label.color": { node: "label", field: "fills", paint: true },
  "label.typography": { node: "label", field: "fontSize" },
};

export const PLUGIN_NAMESPACE = "fundamento";

/** `code.js` with the plan embedded. */
export function pluginSource(plan: FigmaPlan): string {
  return `// Generated by fm projekcioj build; do not edit (Art. I). Fundamento ${plan.fundamento}.
const PLAN = ${JSON.stringify(plan)};
const NAMESPACE = ${JSON.stringify(PLUGIN_NAMESPACE)};
const BINDINGS = ${JSON.stringify(BINDINGS)};

/** The collection of a name, its modes renamed and completed, without duplicating anything. */
async function applyCollections() {
  const existing = await figma.variables.getLocalVariableCollectionsAsync();
  const byName = new Map(existing.map((collection) => [collection.name, collection]));
  const collections = new Map();
  const modeIds = new Map();
  for (const spec of PLAN.collections) {
    // A collection without variables is not created: in a Modelo with an external Aspekto every
    // token hangs on the aspekto Dimensio (Art. IV completeness), so fundamento can be empty.
    if (spec.variables.length === 0) continue;
    const collection = byName.get(spec.name) ?? figma.variables.createVariableCollection(spec.name);
    collections.set(spec.name, collection);
    const ids = {};
    spec.modes.forEach((mode, index) => {
      const known = collection.modes.find((candidate) => candidate.name === mode);
      if (known !== undefined) {
        ids[mode] = known.modeId;
        return;
      }
      const spare = collection.modes[index];
      if (index === 0 && spare !== undefined) {
        collection.renameMode(spare.modeId, mode);
        ids[mode] = spare.modeId;
        return;
      }
      ids[mode] = collection.addMode(mode);
    });
    modeIds.set(spec.name, ids);
  }
  return { collections, modeIds };
}

async function applyVariables(collections, modeIds) {
  const existing = await figma.variables.getLocalVariablesAsync();
  const byName = new Map(existing.map((variable) => [variable.name, variable]));
  const variables = new Map();
  for (const spec of PLAN.collections) {
    const collection = collections.get(spec.name);
    for (const variable of spec.variables) {
      const found =
        byName.get(variable.name) ??
        figma.variables.createVariable(variable.name, collection, variable.type);
      found.hiddenFromPublishing = variable.hidden === true;
      variables.set(variable.name, found);
    }
  }
  // Values last: an alias needs its target to exist.
  for (const spec of PLAN.collections) {
    const ids = modeIds.get(spec.name);
    for (const variable of spec.variables) {
      const found = variables.get(variable.name);
      for (const [mode, value] of Object.entries(variable.values)) {
        const target = value !== null && typeof value === "object" && "alias" in value
          ? figma.variables.createVariableAlias(variables.get(value.alias))
          : value;
        found.setValueForMode(ids[mode], target);
      }
    }
  }
  return variables;
}

/** The node this plugin made for \`key\`, or undefined; identified by shared plugin data. */
function ours(parent, key, value) {
  return parent.children.find(
    (child) => child.getSharedPluginData(NAMESPACE, key) === value,
  );
}

function bind(control, label, bindings, paints, variables) {
  for (const [part, name] of Object.entries(bindings)) {
    const target = BINDINGS[part];
    const variable = variables.get(name);
    if (target === undefined || variable === undefined) continue;
    const node = target.node === "label" ? label : control;
    if (target.paint === true) {
      // Figma binds only the RGB of a variable to a paint; the deckkraft comes from the plan and
      // is set here, in every case — also at 0, so the binding stays visible in the file (F8).
      const paint = (paints || {})[part];
      const bound = figma.variables.setBoundVariableForPaint(
        { type: "SOLID", color: { r: 0, g: 0, b: 0 } },
        "color",
        variable,
      );
      if (paint !== undefined && typeof paint.opacity === "number") bound.opacity = paint.opacity;
      node[target.field] = [bound];
    } else {
      node.setBoundVariable(target.field, variable);
    }
  }
}

function variantName(props) {
  return Object.entries(props)
    .map(([key, value]) => key + "=" + value)
    .join(", ");
}

async function applyComponents(variables) {
  await figma.loadFontAsync({ family: "Inter", style: "Regular" });
  for (const component of PLAN.components) {
    let set = ours(figma.currentPage, "ero", component.set);
    const made = [];
    for (const variant of component.variants) {
      const name = variantName(variant.props);
      const existing = set === undefined ? undefined : ours(set, "variant", name);
      const node = existing ?? figma.createComponent();
      node.name = name;
      node.setSharedPluginData(NAMESPACE, "variant", name);
      node.setSharedPluginData(NAMESPACE, "ero", component.set);
      let control = ours(node, "part", "control");
      let label;
      if (control === undefined) {
        control = figma.createFrame();
        control.setSharedPluginData(NAMESPACE, "part", "control");
        label = figma.createText();
        label.setSharedPluginData(NAMESPACE, "part", "label");
        control.appendChild(label);
        node.appendChild(control);
      } else {
        label = ours(control, "part", "label");
      }
      control.name = "control";
      label.name = "label";
      bind(control, label, variant.bindings, variant.paints, variables);
      if (existing === undefined) made.push(node);
    }
    if (set === undefined) {
      set = figma.combineAsVariants(made, figma.currentPage);
      set.name = component.set;
    }
    set.setSharedPluginData(NAMESPACE, "ero", component.set);
    set.setSharedPluginData(NAMESPACE, "skemo", component.pluginData.fundamento.skemo);
    set.setSharedPluginData(NAMESPACE, "version", component.pluginData.fundamento.version);
    for (const node of made) if (node.parent !== set) set.appendChild(node);
  }
}

/** Applies the whole plan; safe to run again. */
async function applyPlan() {
  const { collections, modeIds } = await applyCollections();
  const variables = await applyVariables(collections, modeIds);
  await applyComponents(variables);
  return {
    collections: PLAN.collections.length,
    variables: variables.size,
    components: PLAN.components.length,
  };
}

if (typeof figma !== "undefined" && typeof figma.closePlugin === "function" && figma.command !== undefined) {
  applyPlan().then((result) => {
    figma.notify(
      "Fundamento " + PLAN.fundamento + ": " + result.variables + " variables applied.",
    );
    figma.closePlugin();
  });
}
`;
}

/** `manifest.json` of the development plugin. */
export function pluginManifest(plan: FigmaPlan): string {
  return `${JSON.stringify(
    {
      name: `Fundamento ${plan.fundamento}: apply plan`,
      id: "fundamento-apply-plan",
      api: "1.0.0",
      main: "code.js",
      editorType: ["figma"],
      documentAccess: "dynamic-page",
      networkAccess: { allowedDomains: ["none"] },
    },
    null,
    2,
  )}\n`;
}
