// The generated Figma development plugin (Spec 003, plan D-12). The maintainer imports it from its
// manifest in Figma desktop; development plugins run on every Figma plan, so the standard path does
// not depend on Organization or Enterprise. It applies `plan.json` — embedded as a constant, since
// a plugin reads no repository files — idempotently: it finds what it made by name and by the
// shared plugin data `fundamento`, updates it, and never duplicates. Nothing else in the file is
// touched. An agent can run the same code through the Figma MCP.
//
// The plugin uses this slice of the Plugin API (the test double covers exactly it):
// variables.getLocalVariableCollectionsAsync/getLocalVariablesAsync, createVariableCollection,
// createVariable, createVariableAlias, setBoundVariableForPaint, collection.addMode/renameMode,
// variable.setValueForMode, createComponent/createFrame/createText, combineAsVariants,
// appendChild, setBoundVariable, set/getSharedPluginData.

import type { FigmaPlan } from "./figma.js";

/** Part property -> the node and field the plugin binds it to (Celo knowledge, Art. VIII). */
const BINDINGS: Readonly<
  Record<string, { node: "control" | "label"; fields: readonly string[]; paint?: boolean }>
> = {
  "surface.fill": { node: "control", fields: ["fills"], paint: true },
  "border.color": { node: "control", fields: ["strokes"], paint: true },
  "border.width": { node: "control", fields: ["strokeWeight"] },
  "box.height": { node: "control", fields: ["minHeight"] },
  "box.width": { node: "control", fields: ["minWidth"] },
  // Inline padding is one value for both sides (F11): binding only the left one left the right
  // side at Figma's default.
  "box.inline-padding": { node: "control", fields: ["paddingLeft", "paddingRight"] },
  "box.gap": { node: "control", fields: ["itemSpacing"] },
  "box.radius": { node: "control", fields: ["cornerRadius"] },
  "label.color": { node: "label", fields: ["fills"], paint: true },
  "label.typography": { node: "label", fields: ["fontSize"] },
};

/**
 * The layout the control needs so its bound measures take effect (F11). Without auto layout Figma
 * ignores padding, gap and minimum sizes, and the frame keeps its default 100 × 100: the label sits
 * centred in a row whose height is at least `box.height` and whose width follows its content.
 */
const CONTROL_LAYOUT: Readonly<Record<string, string>> = {
  layoutMode: "HORIZONTAL",
  primaryAxisAlignItems: "CENTER",
  counterAxisAlignItems: "CENTER",
  primaryAxisSizingMode: "AUTO",
  counterAxisSizingMode: "AUTO",
};

export const PLUGIN_NAMESPACE = "fundamento";

/** `code.js` with the plan embedded. */
export function pluginSource(plan: FigmaPlan): string {
  return `// Generated by fm projekcioj build; do not edit (Art. I). Fundamento ${plan.fundamento}.
const PLAN = ${JSON.stringify(plan)};
const NAMESPACE = ${JSON.stringify(PLUGIN_NAMESPACE)};
const BINDINGS = ${JSON.stringify(BINDINGS)};
const CONTROL_LAYOUT = ${JSON.stringify(CONTROL_LAYOUT)};

/** The collection of a name, its modes renamed and completed, without duplicating anything. */
async function applyCollections() {
  const existing = await figma.variables.getLocalVariableCollectionsAsync();
  const byName = new Map(existing.map((collection) => [collection.name, collection]));
  const collections = new Map();
  const modeIds = new Map();
  for (const spec of PLAN.collections) {
    // A collection without variables is not created: in a Modelo with an external Aspekto every
    // token hangs on the aspekto Dimensio (Art. IV completeness), so fundamento can be empty.
    if (spec.variables.length === 0) continue;
    const collection = byName.get(spec.name) ?? figma.variables.createVariableCollection(spec.name);
    collections.set(spec.name, collection);
    const ids = {};
    spec.modes.forEach((mode, index) => {
      const known = collection.modes.find((candidate) => candidate.name === mode);
      if (known !== undefined) {
        ids[mode] = known.modeId;
        return;
      }
      const spare = collection.modes[index];
      if (index === 0 && spare !== undefined) {
        collection.renameMode(spare.modeId, mode);
        ids[mode] = spare.modeId;
        return;
      }
      ids[mode] = collection.addMode(mode);
    });
    modeIds.set(spec.name, ids);
  }
  return { collections, modeIds };
}

async function applyVariables(collections, modeIds) {
  const existing = await figma.variables.getLocalVariablesAsync();
  const byName = new Map(existing.map((variable) => [variable.name, variable]));
  const variables = new Map();
  for (const spec of PLAN.collections) {
    const collection = collections.get(spec.name);
    for (const variable of spec.variables) {
      const found =
        byName.get(variable.name) ??
        figma.variables.createVariable(variable.name, collection, variable.type);
      found.hiddenFromPublishing = variable.hidden === true;
      variables.set(variable.name, found);
    }
  }
  // Values last: an alias needs its target to exist.
  for (const spec of PLAN.collections) {
    const ids = modeIds.get(spec.name);
    for (const variable of spec.variables) {
      const found = variables.get(variable.name);
      for (const [mode, value] of Object.entries(variable.values)) {
        const target = value !== null && typeof value === "object" && "alias" in value
          ? figma.variables.createVariableAlias(variables.get(value.alias))
          : value;
        found.setValueForMode(ids[mode], target);
      }
    }
  }
  return variables;
}

/** The node this plugin made for \`key\`, or undefined; identified by shared plugin data. */
function ours(parent, key, value) {
  return parent.children.find(
    (child) => child.getSharedPluginData(NAMESPACE, key) === value,
  );
}

function bind(control, label, bindings, paints, variables) {
  for (const [part, name] of Object.entries(bindings)) {
    const target = BINDINGS[part];
    const variable = variables.get(name);
    if (target === undefined || variable === undefined) continue;
    const node = target.node === "label" ? label : control;
    if (target.paint === true) {
      // Figma binds only the RGB of a variable to a paint; the deckkraft comes from the plan and
      // is set here, in every case — also at 0, so the binding stays visible in the file (F8).
      const paint = (paints || {})[part];
      const bound = figma.variables.setBoundVariableForPaint(
        { type: "SOLID", color: { r: 0, g: 0, b: 0 } },
        "color",
        variable,
      );
      if (paint !== undefined && typeof paint.opacity === "number") bound.opacity = paint.opacity;
      for (const field of target.fields) node[field] = [bound];
    } else {
      for (const field of target.fields) node.setBoundVariable(field, variable);
    }
  }
}

function variantName(props) {
  return Object.entries(props)
    .map(([key, value]) => key + "=" + value)
    .join(", ");
}

/**
 * Das Paar aus dem Endstand des vorigen Laufs ("left") und dem Anfangsstand dieses Laufs
 * ("before") gelesen — die Zeilen einzeln zu deuten führt in die Irre (F10b).
 */
function diagnose(report) {
  const planned = report.planned;
  if (!report.found) return "";
  const complete =
    report.created.length === 0 &&
    report.before.children === planned &&
    report.before.marked === planned;
  if (complete) return "";
  if (report.before.marked < report.before.children) {
    return "Ein Kind des Sets stand ohne Markierung da: die Markierung ist verloren gegangen, " +
      "der Knoten nicht.";
  }
  if (report.left === null) {
    return "Am Set steht kein Endstand eines früheren Laufs. Damit lassen sich „nie im Set " +
      "angekommen“ und „zwischen den Läufen verschwunden“ für dieses Set noch nicht trennen; " +
      "der nächste Lauf kann es.";
  }
  if (report.left.children < planned) {
    return "Schon der vorige Lauf hinterließ " + report.left.children + " statt " + planned +
      " Kinder: die Variante ist beim Anlegen nie im Set angekommen.";
  }
  if (report.before.children < report.left.children) {
    return "Der vorige Lauf hinterließ " + report.left.children + " Kinder, dieser fand " +
      report.before.children + ": zwischen den Läufen ist etwas verschwunden.";
  }
  return "";
}

async function applyComponents(variables) {
  await figma.loadFontAsync({ family: "Inter", style: "Regular" });
  const reports = [];
  for (const component of PLAN.components) {
    let set = ours(figma.currentPage, "ero", component.set);
    // How the run found the set, before it changed anything (F10b). Ohne diesen Blick lässt sich
    // hinterher nicht mehr unterscheiden, ob ein Knoten fehlte oder ob er nur seine Markierung
    // verloren hatte — der frisch angelegte Knoten verdeckt beides.
    const mark = (child) => child.getSharedPluginData(NAMESPACE, "variant");
    const before =
      set === undefined
        ? { children: 0, marked: 0, unmarked: [] }
        : {
            children: set.children.length,
            marked: set.children.filter((child) => mark(child) !== "").length,
            unmarked: set.children.filter((child) => mark(child) === "").map((child) => child.name),
          };
    // Was der vorige Lauf am Set hinterlassen hat. Lauf 2 lässt sich nur im Licht von Lauf 1
    // deuten: „71 Kinder beim Start" heißt nur dann „zwischen den Läufen verschwunden", wenn Lauf 1
    // mit 72 geendet hat (F10b). Deshalb legt jeder Lauf seinen Endstand hier ab.
    const stored = set === undefined ? "" : set.getSharedPluginData(NAMESPACE, "after");
    const report = {
      set: component.set,
      found: set !== undefined,
      planned: component.variants.length,
      left: stored === "" ? null : JSON.parse(stored),
      before: before,
      created: [],
      updated: [],
      missing: [],
      extra: [],
      duplicates: [],
      after: { children: 0, marked: 0 },
      diagnosis: "",
    };
    const made = [];
    for (const variant of component.variants) {
      const name = variantName(variant.props);
      const existing = set === undefined ? undefined : ours(set, "variant", name);
      (existing === undefined ? report.created : report.updated).push(name);
      const node = existing ?? figma.createComponent();
      node.name = name;
      node.setSharedPluginData(NAMESPACE, "variant", name);
      node.setSharedPluginData(NAMESPACE, "ero", component.set);
      let control = ours(node, "part", "control");
      let label;
      if (control === undefined) {
        control = figma.createFrame();
        control.setSharedPluginData(NAMESPACE, "part", "control");
        label = figma.createText();
        label.setSharedPluginData(NAMESPACE, "part", "label");
        control.appendChild(label);
        node.appendChild(control);
      } else {
        label = ours(control, "part", "label");
      }
      control.name = "control";
      label.name = "label";
      // Nur Werte aus dem Plan (F13). Figma gibt einem neuen Rahmen und einer neuen Komponente
      // eine weiße Fläche mit, die nicht aus dem Modell stammt und eine durchsichtige Fläche
      // wieder zudeckt. Jede Fläche wird deshalb geleert; was der Plan nennt, setzt die Bindung
      // gleich danach. Das gilt in jedem Lauf, auch in einer Datei, die ein älteres Plugin anlegte.
      node.fills = [];
      node.strokes = [];
      control.fills = [];
      control.strokes = [];
      label.fills = [];
      // Auto layout before any measure is bound: padding, gap and minimum sizes only take effect
      // on an auto-layout frame (F11).
      for (const [field, value] of Object.entries(CONTROL_LAYOUT)) control[field] = value;
      bind(control, label, variant.bindings, variant.paints, variables);
      if (existing === undefined) made.push(node);
    }
    if (set === undefined) {
      set = figma.combineAsVariants(made, figma.currentPage);
      set.name = component.set;
    }
    set.setSharedPluginData(NAMESPACE, "ero", component.set);
    set.setSharedPluginData(NAMESPACE, "skemo", component.pluginData.fundamento.skemo);
    set.setSharedPluginData(NAMESPACE, "version", component.pluginData.fundamento.version);
    for (const node of made) if (node.parent !== set) set.appendChild(node);
    // Symmetric (F10): the plan against the file, in both directions, with names. The finding
    // behind this was a document that held 71 of 72 variants while nothing said so.
    const planned = component.variants.map((variant) => variantName(variant.props));
    const present = set.children.map((child) => child.name);
    report.missing = planned.filter((name) => present.indexOf(name) === -1);
    report.extra = present.filter((name) => planned.indexOf(name) === -1);
    report.duplicates = present.filter(
      (name, index) => present.indexOf(name) !== index && report.duplicates.indexOf(name) === -1,
    );
    // Wie der Lauf das Set hinterlässt, Markierungen eingeschlossen. Haftet eine Markierung im
    // Werkzeug nicht, sagt das schon dieser Lauf und nicht erst der nächste über den Umweg
    // „created: 1" (F10b).
    report.after = {
      children: set.children.length,
      marked: set.children.filter((child) => mark(child) !== "").length,
    };
    report.diagnosis = diagnose(report);
    // Ohne Zeitstempel: Zwei gleiche Läufe hinterlassen denselben Stand, sonst wäre der Lauf nicht
    // mehr idempotent.
    set.setSharedPluginData(NAMESPACE, "after", JSON.stringify(report.after));
    reports.push(report);
  }
  return reports;
}

/** Applies the whole plan; safe to run again. Returns the report of this run (F10). */
async function applyPlan() {
  const { collections, modeIds } = await applyCollections();
  const variables = await applyVariables(collections, modeIds);
  const components = await applyComponents(variables);
  const warnings = [];
  for (const report of components) {
    // Ein zweiter Lauf, der in einem vorgefundenen Set etwas anlegt, darf nie still durchgehen
    // (F10b): Entweder fehlte der Knoten, oder er hat seine Markierung verloren — beides ist ein
    // Befund, kein Normalfall.
    if (report.found && report.created.length > 0) {
      warnings.push(
        report.set + ": Das Set war vorgefunden, trotzdem wurden " + report.created.length +
          " Variante(n) neu angelegt (" + report.created.join("; ") + "). Beim Start trug es " +
          report.before.children + " Kinder, davon " + report.before.marked + " markiert" +
          (report.before.unmarked.length === 0
            ? ""
            : ", ohne Markierung: " + report.before.unmarked.join("; ")) +
          ".",
      );
    }
    if (report.diagnosis !== "") warnings.push(report.set + ": " + report.diagnosis);
    if (report.after.marked !== report.after.children) {
      warnings.push(
        report.set + ": " + (report.after.children - report.after.marked) +
          " von " + report.after.children +
          " Kindern sind nach dem Lauf ohne Markierung — der nächste Lauf würde sie nicht " +
          "wiederfinden und neu anlegen.",
      );
    }
    if (report.duplicates.length > 0) {
      warnings.push(
        report.set + ": " + report.duplicates.length +
          " Variantenname(n) doppelt (" + report.duplicates.join("; ") + ").",
      );
    }
    if (report.missing.length === 0 && report.extra.length === 0) continue;
    warnings.push(
      report.set + ": " + report.missing.length + " fehlen" +
        (report.missing.length === 0 ? "" : " (" + report.missing.join("; ") + ")") +
        ", " + report.extra.length + " überzählig" +
        (report.extra.length === 0 ? "" : " (" + report.extra.join("; ") + ")"),
    );
  }
  return {
    fundamento: PLAN.fundamento,
    collections: PLAN.collections.length,
    variables: variables.size,
    components: components,
    warnings: warnings,
  };
}

/** One place for the report: everything in the console, the headline in the toast (F10). */
function announce(result) {
  console.log(
    "Fundamento " + result.fundamento + " – Bericht:" + "\\n" + JSON.stringify(result, null, 2),
  );
  const counted = result.components
    .map((report) =>
      report.set + " " + report.created.length + " neu, " + report.updated.length + " aktualisiert",
    )
    .join("; ");
  const headline =
    result.warnings.length === 0
      ? "Fundamento " + result.fundamento + ": " + result.variables + " Variablen, " + counted + "."
      : "Fundamento " + result.fundamento + ": " + result.warnings.length +
        " Warnung(en) — " + result.warnings.join(" | ");
  figma.notify(
    headline + " Der ganze Bericht steht in der Konsole.",
    result.warnings.length === 0 ? undefined : { error: true, timeout: 10000 },
  );
}

if (typeof figma !== "undefined" && typeof figma.closePlugin === "function" && figma.command !== undefined) {
  applyPlan()
    .then((result) => {
      announce(result);
      figma.closePlugin();
    })
    // A rejection used to disappear: no toast, no console, a plugin that seemed to do nothing.
    .catch((error) => {
      console.error("Fundamento " + PLAN.fundamento + " – Lauf fehlgeschlagen:", error);
      figma.notify(
        "Fundamento " + PLAN.fundamento + ": Lauf fehlgeschlagen — " + String(error && error.message ? error.message : error) +
          ". Einzelheiten in der Konsole.",
        { error: true, timeout: 10000 },
      );
      figma.closePlugin();
    });
}
`;
}

/** `manifest.json` of the development plugin. */
export function pluginManifest(plan: FigmaPlan): string {
  return `${JSON.stringify(
    {
      name: `Fundamento ${plan.fundamento}: apply plan`,
      id: "fundamento-apply-plan",
      api: "1.0.0",
      main: "code.js",
      editorType: ["figma"],
      documentAccess: "dynamic-page",
      networkAccess: { allowedDomains: ["none"] },
    },
    null,
    2,
  )}\n`;
}
