// React Celo (Spec 003, FR-08, plan D-08, contracts/projekcioj §4): one thin wrapper per Ero that
// renders the Web Component. Props are typed from the Skemo (same names, camelCase; the same
// values as string unions); icon slots take React nodes. One behaviour implementation, the
// element, serves React 18 and 19 alike. Pure.

import type { LoadedEro } from "@fundamento/modelo";
import type { Celo, CeloInput, GeneratedFile } from "../../build.js";
import { GENERATED_DIR, namesOf } from "../web-component/web-component.js";

const camel = (name: string) =>
  name.replace(/-([a-z0-9])/g, (_match, letter: string) => letter.toUpperCase());

/** `Butono` for `butono`. */
export function componentName(ero: LoadedEro["ero"]): string {
  return namesOf(ero).className.slice(2);
}

function propType(prop: LoadedEro["skemo"]["props"][number]): string {
  switch (prop.kind) {
    case "enum":
      return (prop.values ?? []).map((value) => JSON.stringify(value)).join(" | ");
    case "boolean":
      return "boolean";
    case "number":
      return "number";
    default:
      return "string";
  }
}

/** The props interface of one Ero: the Skemo props, the icon slots and children. */
function propsInterface(entry: LoadedEro): string {
  const name = componentName(entry.ero);
  const props = entry.skemo.props;
  const iconSlots = entry.skemo.slots.filter((slot) => slot.decorative === true);
  const fields = [
    ...props.map((prop) => `  ${camel(prop.name)}?: ${propType(prop)};`),
    ...iconSlots.map((slot) => `  ${camel(slot.name)}?: ReactNode;`),
    "  children?: ReactNode;",
  ];
  return `
/** Props of <${name}>: the Skemo props of ${entry.ero.name}, plus HTML attributes for the element. */
export interface ${name}Props extends Omit<HTMLAttributes<HTMLElement>, ${props
    .map((prop) => JSON.stringify(camel(prop.name)))
    .join(" | ")} | "children"> {
${fields.join("\n")}
}
`;
}

function wrapper(entry: LoadedEro): string {
  const { tag } = namesOf(entry.ero);
  const name = componentName(entry.ero);
  const props = entry.skemo.props;
  const iconSlots = entry.skemo.slots.filter((slot) => slot.decorative === true);
  const attributes = props.map((prop) =>
    prop.kind === "boolean"
      ? `    "${prop.name}": ${camel(prop.name)} === true ? true : undefined,`
      : `    "${prop.name}": ${camel(prop.name)},`,
  );
  const slots = iconSlots.map(
    (slot) =>
      `    ${camel(slot.name)} === undefined ? null : createElement("span", { slot: "${slot.name}", key: "${slot.name}" }, ${camel(slot.name)}),`,
  );
  const names = [
    ...props.map((prop) => camel(prop.name)),
    ...iconSlots.map((slot) => camel(slot.name)),
  ];
  return `${propsInterface(entry)}
/** <${tag}> for React 18 and 19. */
export const ${name} = forwardRef<HTMLElement, ${name}Props>(function ${name}(
  { ${names.join(", ")}, children, ...rest },
  ref,
) {
  ensureDefined();
  const attributes: Record<string, unknown> = {
${attributes.join("\n")}
  };
  for (const key of Object.keys(attributes)) if (attributes[key] === undefined) delete attributes[key];
  return createElement(
    "${tag}",
    { ...rest, ...attributes, ref },
${slots.join("\n")}
    children,
  );
});
`;
}

/**
 * The React wrappers of `eroj`, importing `defineEroj` from `importPath`. With `typesOnly` the
 * props interfaces alone are written, for the type declarations of a Make Kit.
 */
export function reactSource(
  eroj: readonly LoadedEro[],
  importPath: string,
  options: { typesOnly?: boolean } = {},
): string {
  if (options.typesOnly === true) {
    return `import type { HTMLAttributes, ReactNode } from "react";
${eroj.map((entry) => propsInterface(entry)).join("")}`;
  }
  return `import { createElement, forwardRef, type HTMLAttributes, type ReactNode } from "react";
import { defineEroj } from "${importPath}";

let defined = false;

/**
 * Registers the elements on the first render, not on import: in a bundle the wrapper and the
 * elements can be in one import cycle, where the class is not initialised yet at import time.
 * Server-side rendering never reaches this either, because it has no customElements.
 */
function ensureDefined(): void {
  if (defined || typeof customElements === "undefined") return;
  defined = true;
  defineEroj();
}
${eroj.map(wrapper).join("")}`;
}

export const REACT_CELO: Celo = {
  name: "react",
  generate({ modelo }: CeloInput): GeneratedFile[] {
    const text = `// Generated by fm projekcioj build from the Skemo; do not edit (Art. I).
${reactSource(modelo.eroj, "./index.js")}`;
    return [{ path: `${GENERATED_DIR}/react.ts`, text }];
  },
};
