// Code Connect Celo (Spec 003, FR-10, plan D-13). An additional projection of the mapping that the
// Skemo already is: Figma component set, property names and values are derived, never maintained.
// Code Connect needs Organization or Enterprise, so the standard path (the Figma plan plus get_ero)
// never depends on these files; they are generated only when the component's URL is given, and the
// maintainer publishes them in the test account. Pure: the URL comes in through `env`.

import type { LoadedEro } from "@fundamento/modelo";
import type { Celo, CeloInput, GeneratedFile } from "../../build.js";
import { componentName } from "../react/react.js";
import { namesOf } from "../web-component/web-component.js";

/** `FUNDAMENTO_FIGMA_BUTONO_URL`: where the component of `ero` lives in the test account. */
export function codeConnectUrlVariable(ero: string): string {
  return `FUNDAMENTO_FIGMA_${ero.replaceAll("-", "_").toUpperCase()}_URL`;
}

export type Env = Readonly<Record<string, string | undefined>>;

/** Why the Celo wrote nothing, or `undefined` when it can write. */
export function skipReason(env: Env, eroj: readonly string[] = ["butono"]): string | undefined {
  const missing = eroj.map(codeConnectUrlVariable).filter((name) => (env[name] ?? "") === "");
  return missing.length === 0
    ? undefined
    : `Code Connect (optional, Organization/Enterprise): no component URL given, so nothing was written. Set ${missing.join(", ")} to the Figma URL of the component set.`;
}

const enumProps = (entry: LoadedEro) => entry.skemo.props.filter((prop) => prop.kind === "enum");

/** One Code Connect mapping per Skemo prop: enum, boolean or string. */
function propMappings(entry: LoadedEro): string {
  return entry.skemo.props
    .map((prop) => {
      if (prop.kind === "enum") {
        const values = (prop.values ?? []).map((value) => `"${value}": "${value}"`).join(", ");
        return `    ${prop.name}: figma.enum("${prop.name}", { ${values} }),`;
      }
      if (prop.kind === "boolean") return `    ${prop.name}: figma.boolean("${prop.name}"),`;
      return `    ${prop.name}: figma.string("${prop.name}"),`;
    })
    .join("\n");
}

function reactFile(entry: LoadedEro, url: string): string {
  const name = componentName(entry.ero);
  const props = propMappings(entry);
  const attributes = enumProps(entry)
    .map((prop) => `${prop.name}={props.${prop.name}}`)
    .join(" ");
  return `// Generated by fm projekcioj build from the Skemo; do not edit (Art. I).
import figma from "@figma/code-connect";
import { ${name} } from "@fundamento/eroj/react";

figma.connect(${name}, "${url}", {
  props: {
${props}
  },
  example: (props) => <${name} ${attributes}>{props.label}</${name}>,
});
`;
}

function htmlFile(entry: LoadedEro, url: string): string {
  const { tag } = namesOf(entry.ero);
  const props = propMappings(entry);
  const attributes = enumProps(entry)
    .map((prop) => `${prop.name}="\${props.${prop.name}}"`)
    .join(" ");
  return `// Generated by fm projekcioj build from the Skemo; do not edit (Art. I).
import figma, { html } from "@figma/code-connect/html";

figma.connect("${url}", {
  props: {
${props}
  },
  example: (props) => html\`<${tag} ${attributes}>\${props.label}</${tag}>\`,
});
`;
}

export const CODE_CONNECT_CELO: Celo = {
  name: "code-connect",
  generate({ modelo, env = {} }: CeloInput): GeneratedFile[] {
    const eroj = modelo.eroj.filter(
      (entry) => (env[codeConnectUrlVariable(entry.ero.name)] ?? "") !== "",
    );
    if (eroj.length === 0) return [];
    const files = eroj.flatMap((entry) => {
      const url = env[codeConnectUrlVariable(entry.ero.name)] ?? "";
      return [
        { path: `code-connect/${entry.ero.name}.figma.tsx`, text: reactFile(entry, url) },
        { path: `code-connect/${entry.ero.name}.figma.ts`, text: htmlFile(entry, url) },
      ];
    });
    return [
      ...files,
      {
        path: "code-connect/figma.config.json",
        text: `${JSON.stringify(
          {
            codeConnect: {
              parser: "react",
              include: ["*.figma.tsx", "*.figma.ts"],
              importPaths: { "@fundamento/eroj/react": "@fundamento/eroj/react" },
            },
          },
          null,
          2,
        )}\n`,
      },
    ];
  },
};
