// Tailwind v4 Celo (Spec 003, FR-06, plan D-06, Constitution v1.6 Art. XII). One `@theme inline`
// block: every token with a Tailwind namespace under its Tailwind NomRegulo name
// (`--color-fm-action-primary-rest`), valued with the CSS Celo's variable, so utilities such as
// `bg-fm-action-primary-rest` follow the data-fm-* switching of the CSS Celo. `inline` makes
// Tailwind emit the var() into each utility instead of re-declaring the value. No prefix(): it
// would rename every class of the host project. Pure.

import { isNoTarget, nomRegulo } from "@fundamento/modelo";
import type { Celo, CeloInput, GeneratedFile } from "../../build.js";

export const TAILWIND_CELO: Celo = {
  name: "tailwind",
  generate({ modeloJson }: CeloInput): GeneratedFile[] {
    const lines = [...modeloJson.tokens]
      .sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0))
      .flatMap((token) => {
        const key = nomRegulo("tailwind").derive(token.name, token.type);
        return isNoTarget(key) ? [] : [`  ${key}: var(${nomRegulo("css").derive(token.name)});`];
      });
    const text = [
      "/* Fundamento theme for Tailwind v4. Import after tailwindcss and after the CSS Celo",
      "   (fundamento.css). Generated by fm projekcioj build; do not edit. */",
      "",
      "@theme inline {",
      ...lines,
      "}",
      "",
    ].join("\n");
    return [{ path: "tailwind/fundamento.tailwind.css", text }];
  },
};
